version: '3.8'
services:
  postgres:
    image: postgres:15
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # Fix: Use env var
    ports:
      - "5432:5432"

  graphql-engine:
    image: hasura/graphql-engine:v2.42.0
    ports:
      - "8081:8080"
    restart: always
    environment:
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres # Fix: Use env var
      PG_DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres # Fix: Use env var
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      HASURA_GRAPHQL_DEV_MODE: "false"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, query-log
      HASURA_GRAPHQL_SERVER_NAME: "Production - Clinikdna Hasura ⚠️"
      HASURA_GRAPHQL_ADMIN_SECRET: ${HASURA_ADMIN_SECRET_PROD} # Fix: Use env var
    depends_on:
      - postgres

volumes:
  db_data: