global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alert-manager:9093']

rule_files:
  - '/etc/prometheus/alert_rules.yml'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'hasura-dev'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['hasura-dev:8080']
    # authorization:
    #   type: Bearer
    #   credentials: "{{ env `HASURA_METRICS_SECRET_DEV` }}"

  - job_name: 'hasura-prod'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['hasura-prod:8080']
    # authorization:
    #   type: Bearer
    #   credentials: "{{ env `HASURA_METRICS_SECRET_PROD` }}"