route:
  group_by: ['alertname', 'job']
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1h
  receiver: 'discord'

receivers:
  - name: 'discord'
    webhook_configs:
      - url: 'http://discord-alerts:9087'
        send_resolved: true