name: Deploy Development Environment

on:
  push:
    branches:
      - main
    paths:
      - 'docker-compose.dev.yml'
      - 'src/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and run dev environment
        env:
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          HASURA_ADMIN_SECRET_DEV: ${{ secrets.HASURA_ADMIN_SECRET_DEV }}
        run: |
          docker-compose -f docker-compose.dev.yml up -d --build
          sleep 10
          curl -f http://localhost:8080/healthz || exit 1

      - name: Stop dev environment
        run: docker-compose -f docker-compose.dev.yml down